### ISSUE TITLE
esbuild-plugin-filesize fails with Unexpected token: punc (:) because it tries to parse sourcemap files

### ISSUE THREAD

**Issue by Lucas-C** [linbudu599/Blog#40]
**To reproduce the bug**
* use an empty input `index.ts` file
* use the following `package.json`:
```json
{
  "name": "bug-repro-esbuild-plugin-filesize",
  "version": "1.0.0",
  "devDependencies": {
    "esbuild": "0.14.54",
    "esbuild-plugin-filesize": "0.3.0"
  }
}
```
* use the following `build.js`:
```javascript
require('esbuild').build({
  entryPoints: ['index.ts'],
  sourcemap: true,
  outdir: 'dist',
  plugins: [require('esbuild-plugin-filesize').esbuildPluginFileSize()],
})
```
* run those commands:
```
npm install
node build.js
```

**Error raised**
```
X [ERROR] [plugin fileSize] Unexpected token: punc (:)

    C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:554:10:
      554 │     throw new JS_Parse_Error(message, filename, line, col, pos);
          ╵           ^

    at js_error (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:554:11)
    at croak (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1278:9)
    at token_error (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1286:9)
    at unexpected (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1292:9)
    at semicolon (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1330:56)
    at simple_statement (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1587:73)
    at statement (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1373:47)
    at _embed_tokens_wrapper (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1343:26)
    at block_ (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:2178:20)
    at statement (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1407:29)

  This error came from the "onEnd" callback registered here:

    C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild-plugin-filesize\src\lib\esbuild-plugin-filesize.js:38:12:
      38 │             onEnd(async () => {
         ╵             ~~~~~

    at setup (C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild-plugin-filesize\src\lib\esbuild-plugin-filesize.js:38:13)
    at handlePlugins (C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:855:23)
    at Object.buildOrServe (C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:1149:7)
    at C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:2109:14)
    at Object.build (C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:1956:51)
    at Object.<anonymous> (C:\bug-repro-esbuild-plugin-filesize\build.js:1:20)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)

C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:1624
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:554:10: ERROR: [plugin: fileSize] Unexpected token: punc (:)
    at failureErrorWithLog (C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:1624:15)
    at C:\bug-repro-esbuild-plugin-filesize\node_modules\esbuild\lib\main.js:1266:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      id: '',
      pluginName: 'fileSize',
      text: 'Unexpected token: punc (:)',
      location: {
        file: 'C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js',
        namespace: 'file',
        line: 554,
        column: 10,
        length: 0,
        lineText: '    throw new JS_Parse_Error(message, filename, line, col, pos);\n' +
          '    at js_error (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:554:11)\n' +
          '    at croak (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1278:9)\n' +
          '    at token_error (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1286:9)\n' +
          '    at unexpected (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1292:9)\n' +
          '    at semicolon (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1330:56)\n' +
          '    at simple_statement (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1587:73)\n' +
          '    at statement (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1373:47)\n' +
          '    at _embed_tokens_wrapper (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1343:26)\n' +
          '    at block_ (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:2178:20)\n' +
          '    at statement (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\terser\\dist\\bundle.min.js:1407:29)',
        suggestion: ''
      },
      notes: [
        {
          text: 'This error came from the "onEnd" callback registered here:',
          location: {
            file: 'C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\esbuild-plugin-filesize\\src\\lib\\esbuild-plugin-filesize.js',
            namespace: 'file',
            line: 38,
            column: 12,
            length: 5,
            lineText: '            onEnd(async () => {\n' +
              '    at setup (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\esbuild-plugin-filesize\\src\\lib\\esbuild-plugin-filesize.js:38:13)\n' +
              '    at handlePlugins (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\esbuild\\lib\\main.js:855:23)\n' +
              '    at Object.buildOrServe (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\esbuild\\lib\\main.js:1149:7)\n' +
              '    at C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\esbuild\\lib\\main.js:2110:17\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.build (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\esbuild\\lib\\main.js:2109:14)\n' +
              '    at Object.build (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\node_modules\\esbuild\\lib\\main.js:1956:51)\n' +
              '    at Object.<anonymous> (C:\\DevHome\\snapshots\\bug-repro-esbuild-plugin-filesize\\build.js:1:20)\n' +
              '    at Module._compile (node:internal/modules/cjs/loader:1126:14)',
            suggestion: ''
          }
        }
      ],
      detail: JS_Parse_Error [SyntaxError]: Unexpected token: punc (:)
          at js_error (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:554:11)
          at croak (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1278:9)
          at token_error (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1286:9)
          at unexpected (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1292:9)
          at semicolon (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1330:56)
          at simple_statement (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1587:73)
          at statement (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1373:47)
          at _embed_tokens_wrapper (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1343:26)
          at block_ (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:2178:20)
          at statement (C:\bug-repro-esbuild-plugin-filesize\node_modules\terser\dist\bundle.min.js:1407:29) {
        filename: '0',
        line: 2,
        col: 11,
        pos: 13
      }
    }
  ],
  warnings: []
}
```

**Environment**
* Windows 10
* NodeJS v16.17.0
* npm 8.15.0

**Workaround**
Do not generate sourcemap files

**Comment by Lucas-C** [comment]
PR submitted to fix this: https://github.com/LinbuduLab/nx-plugins/pull/92
